### PR TITLE
Fixes #1832 Storybook: Uncaught Exception (in promise) Error: Type QueryType must define one or more fields. 

### LINKED ISSUE #1832: Storybook: Uncaught Exception (in promise) Error: Type QueryType must define one or more fields.
image

### PR DESCRIPTION
**Pull request by tonylee80**
- initialize mock repo in MockClient by calling mock fetch

### Summary
🐛🔄📚

Updated storybook preview to use `get` method instead of `requestSchema` for loading FHIR schemas. This fixed a bug where the Patient schema was not loaded correctly.

> _`requestSchema` gone_
> _`get` method takes its place now_
> _storybook bug fixed_

### Walkthrough
*  Replaced `requestSchema` method with `get` method to fix storybook loading bug ([link](https://github.com/medplum/medplum/pull/1866/files?diff=unified&w=0#diff-ecaed68104ad33d3df2ba0f62413867d09258ce816c678a9c9216b45de48c4bfL20-R20))

### CODE REVIEW

File: packages/react/.storybook/preview.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ export const parameters = {
 };
 
 const medplum = new MockClient();
-medplum.requestSchema('Patient');
+medplum.get('/');
```
Comment (tonylee80) [inline packages/react/.storybook/preview.js:20]: Calling `.get` to call mockFetch() which will initialize the mock repo to resolve race condition of Mock Repo initiated in MockClient.

https://github.com/medplum/medplum/blob/8d381d131c4f32a0fabd301b5fd227960e2d2928/packages/mock/src/client.ts#L183. Any subsequent graphql calls (like medplum.requestSchema) will no longer throw exception.

**Review by mattwiller — APPROVED** [review]

**Review by codyebberson — APPROVED** [review]
