### PR TITLE
[Medplum Provider app] Various fixes and touchups

### LINKED ISSUE #4485: Need to add sexual orientation observation data capture to provider app
http://hl7.org/fhir/us/core/STU6.1/StructureDefinition-us-core-observation-sexual-orientation.html

### PR DESCRIPTION
**Pull request by mattlong**
* Added Sexual Orientation section to `PatientSummary`
* Calculate correct gender icon instead of using a hard-coded icon in `PatientSummary`
* Onboarding page functional now using `ResourceForm`
* More accurate links to appointments and encounters in `PatientSummary`
* Corrected binding in MedicationRequest dialog in `PatientSummary`

Fixes #4485

### CODE REVIEW

File: packages/react/src/PatientSummary/SexualOrientation.tsx [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+            <CodeableConceptDisplay value={sexualOrientation.valueCodeableConcept} />
+          </Badge>
+        </Box>
+      ) : (
+        <Text>(none)</Text>
+      )}
+      <Modal opened={opened} onClose={close} title="Set Sexual Orientation">
+        <Form onSubmit={handleSubmit}>
+          <Stack>
+            <Radio.Group name="sexualOrientation" label="Sexual Orientation" required>
```
Comment (codyebberson) [inline packages/react/src/PatientSummary/SexualOrientation.tsx:128]: 🤔 

I wonder if we should have a "radio button" option on `<CodeableConceptInput>`?  Most of the logic would be the same, just a different presentation mode.  That would have saved a lot of code here.

File: packages/core/src/constants.ts [hunk 2]
```diff
@@ -9,3 +9,4 @@ export const ICD10 = 'http://hl7.org/fhir/sid/icd-10';
 // common http-based origins useful for avoiding false-positives about preferring https over http,
 // e.g. https://rules.sonarsource.com/javascript/type/Security%20Hotspot/RSPEC-5332/
 export const HTTP_HL7_ORG = 'http://hl7.org';
+export const HTTP_TERMINOLOGY_HL7_ORG = 'http://terminology.hl7.org';
```
Comment (codyebberson) [inline packages/core/src/constants.ts:12]: 👍 ✅

File: packages/react/src/PatientSummary/MedicationDialog.tsx [hunk 3]
```diff
@@ -39,7 +39,7 @@ export function MedicationDialog(props: MedicationDialogProps): JSX.Element {
           name="request"
           path="MedicationRequest.medication[x]"
           data-autofocus={true}
-          binding="https://app.medplum.com/ValueSet/16d6f7b7-7eeb-4d0e-a83b-83be082aa10b"
+          binding={HTTP_HL7_ORG + '/fhir/ValueSet/medication-codes'}
```
Comment (codyebberson) [inline packages/react/src/PatientSummary/MedicationDialog.tsx:42]: 👍 ✅

**Review by codyebberson — APPROVED** [review]
lgtm 👍
