### PR TITLE
fix(agent): harden reconnect logic

### LINKED ISSUE #5329: Harden Agent reconnect logic
We have some reconnect logic for Medplum Agent and we have a heartbeat protocol for the Agent WebSocket connection but currently the heartbeat being missed does not trigger a reconnect, only a full close of the WebSocket does. We could stitch those two mechanics together to harden the Agent reconnect logic

### PR DESCRIPTION
**Pull request by ThatOneBro**
In this PR, we swap in the `ReconnectingWebSocket` implementation to the Agent's client-side WebSocket, and also add a force reconnect when we detect more than `MAX_MISSED_HEARTBEATS` have been missed. 

Fixes #5329

### CODE REVIEW

File: packages/core/src/websockets/reconnecting-websocket.ts [hunk 1]
```diff
@@ -121,24 +122,27 @@ export type Message = string | ArrayBuffer | Blob | ArrayBufferView;
 
 let didWarnAboutMissingWebSocket = false;
 
-export class ReconnectingWebSocket extends TypedEventTarget<WebSocketEventMap> implements IReconnectingWebSocket {
+export class ReconnectingWebSocket<BType extends string = BinaryType>
```
Comment (mattlong) [inline packages/core/src/websockets/reconnecting-websocket.ts:125]: I'm not very familiar with `WebSocket.BinaryType`, but the fact that it is both 1) used a type generic that gets narrowed in the constructor and 2) is mutable within this class feels a bit off which I think is evident by all the type-casting that is being done around `BType`. Would it be reasonable to get rid of the generic and just have the binaryType getter and setter functions just work with a type `string` or `BinaryType` instead?

Related, looking at the other places in our code that mention binaryType, it's unclear which BinaryType(s) should be settable. Is it really just `"arraybuffer" | "blob"` or should `"nodebuffer" | "fragments"` also be acceptable?

Comment (ThatOneBro) [reply packages/core/src/websockets/reconnecting-websocket.ts:125]: It depends on the environment. In the browser `nodebuffer` and `fragments` don't exist

Comment (ThatOneBro) [reply packages/core/src/websockets/reconnecting-websocket.ts:125]: The reason the typecasting is done is because the default for `BinaryType` comes from builtin typing but it assumes the browser context

Comment (ThatOneBro) [reply packages/core/src/websockets/reconnecting-websocket.ts:125]: Ideally we would be able to pass the `WebSocket` class type as a generic and pull the `binaryType` from there, but the `WebSocket` global type from the built-in types does not include that information until you construct the WebSocket itself (it's just an interface)

Comment (ThatOneBro) [reply packages/core/src/websockets/reconnecting-websocket.ts]: Okay so I was able to achieve the (almost) ideal solution by creating a generic interface with the default being the global `WebSocket` interface and reading the type of `binaryType` off of the passed in implementation. Let me know if this is better and/or if it makes more sense now what is happening

**Review by codyebberson — APPROVED** [review]

File: packages/core/src/websockets/reconnecting-websocket.ts (hunk 1 above)
Comment (mattlong) [reply packages/core/src/websockets/reconnecting-websocket.ts]: Nice! Thank you for the explanation; looks great!

**Review by mattlong — APPROVED** [review]
