### PR TITLE
Fix warning about missing key in ChooseScopeForm

### LINKED ISSUE #6098: [ChooseScopeForm] Warning: Each child in a list should have a unique "key" prop
Image

### PR DESCRIPTION
**Pull request by mattwiller**
Resolves #6098

### CODE REVIEW

File: packages/react/src/auth/ChooseScopeForm.tsx [hunk 1]
```diff
@@ -62,10 +62,10 @@ export function ChooseScopeForm(props: ChooseScopeFormProps): JSX.Element {
               ];
             }
             return (
-              <>
+              <div key={scopeName + '_group'}>
```
Comment (codyebberson) [inline packages/react/src/auth/ChooseScopeForm.tsx:65]: If you don't actually need a `<div>`, you can use `Fragment` (imported `from 'react';`)

That's the syntactic way to add a `key` prop to a fragment.

```suggestion
              <Fragment key={scopeName + '_group'}>
```

**Review by ThatOneBro — APPROVED** [review]

**Review by codyebberson — APPROVED** [review]
