### PR TITLE
Fix `:missing` modifier for token search params

### LINKED ISSUE #3217: `:missing` not working for token search parameters
## Repro
1. Create this patient
```json
{
  "resourceType": "Patient",
  "name": [
    {
      "given": [
        "Without"
      ],
      "family": "Email"
    }
  ]
}
```

2. Go to the Medplum app: `/Patient?email:missing=true`

## Expected Behavior
This patient should be part of the search results

## Actual Behavior
No patients are returned

## Root Cause
The issue lies in the `buildWhere` function in token.ts
https://github.com/medplum/medplum/blob/594e11d323367e018b56df1d1f4b61c1a1c2dd98/packages/server/src/fhir/lookups/token.ts#L108-L125

The SQL that is produced is: 

```sql
SELECT    "Patient"."id",
          "Patient"."content"
FROM      "Patient"
LEFT JOIN "Patient_Token" AS "T1"
ON        (
                    "Patient"."id"="T1"."resourceId"
          AND       "T1"."code"=$1
          AND       "T1"."value"=$2)
WHERE     (
                    "Patient"."deleted"=$3
          AND       (
                              "Patient"."compartments" IS NOT NULL
                    AND       "Patient"."compartments"&&array[$4,$5]::uuid[])
          AND       "T1"."resourceId" IS NOT NULL)
GROUP BY  "Patient"."id"
ORDER BY  "Patient"."lastUpdated" DESC limit 21
```

The changes needed are: 
1. Remove ` AND       "T1"."value"=$2` from the ON conditions
2. Edit this WHERE statement to depend on whether missing is `true` or `false`
```sql 
AND       "T1"."resourceId" IS NOT NULL
```

### PR DESCRIPTION
**Pull request by rahul1**
Fixes #3217 

Example search: `Patient?email:missing=true`

## Before

```sql
SELECT    "Patient"."id",
          "Patient"."content"
FROM      "Patient"
LEFT JOIN "Patient_Token" AS "T1"
ON        (
                    "Patient"."id"="T1"."resourceId"
          AND       "T1"."code"=$1
          AND       "T1"."value"=$2)
WHERE     (
                    "Patient"."deleted"=$3
          AND       (
                              "Patient"."compartments" IS NOT NULL
                    AND       "Patient"."compartments"&&array[$4,$5]::uuid[])
          AND       "T1"."resourceId" IS NOT NULL)
GROUP BY  "Patient"."id"
ORDER BY  "Patient"."lastUpdated" DESC limit 21
```

## After
```sql
SELECT    "Patient"."id",
          "Patient"."content"
FROM      "Patient"
LEFT JOIN "Patient_Token" AS "T1"
ON        (
                    "Patient"."id"="T1"."resourceId"
          AND       "T1"."code"=$1)
WHERE     (
                    "Patient"."deleted"=$3
          AND       (
                              "Patient"."compartments" IS NOT NULL
                    AND       "Patient"."compartments"&&array[$4,$5]::uuid[])
          AND       "T1"."resourceId" IS NULL)
GROUP BY  "Patient"."id"
ORDER BY  "Patient"."lastUpdated" DESC limit 21
```

### CODE REVIEW

File: packages/server/src/fhir/lookups/token.ts [hunk 1]
```diff
@@ -113,13 +115,14 @@ export class TokenTable extends LookupTable<Token> {
...
     ]);
-    joinOnExpression.expressions.push(buildWhereExpression(joinName, filter));
+    const whereExpression = buildWhereExpression(joinName, filter);
+    if (whereExpression) {
+      joinOnExpression.expressions.push(whereExpression);
+    }
+
     selectQuery.leftJoin(tableName, joinName, joinOnExpression);
 
-    // If the filter is "not equals", then we're looking for ID=null
```
Comment (codyebberson) [inline packages/server/src/fhir/lookups/token.ts:119]: Please keep these comments, they are useful.

File: packages/server/src/fhir/lookups/token.ts [hunk 2]
```diff
@@ -367,30 +414,39 @@ async function getExistingValues(client: PoolClient, resourceType: ResourceType,
...
+    const expression = buildWhereCondition(tableName, filter.operator, option);
+    if (expression) {
+      subExpressions.push(expression);
+    }
+  }
+  if (subExpressions.length > 0) {
+    return new Disjunction(subExpressions);
   }
-  return disjunction;
+  return undefined;
```
Comment (codyebberson) [inline packages/server/src/fhir/lookups/token.ts:428]: What is the case where `subExpressions.length === 0`?

File: packages/server/src/fhir/lookups/token.ts [hunk 3]
```diff
@@ -367,30 +414,39 @@ async function getExistingValues(client: PoolClient, resourceType: ResourceType,
...
       : systemCondition;
   } else {
-    return buildValueCondition(tableName, operator, query);
+    if (operator === FhirOperator.IN) {
+      return buildInValueSetCondition(tableName, query);
+    }
+    if (shouldCompareTokenValue(operator)) {
+      return buildValueCondition(tableName, operator, query);
+    }
+    return undefined;
```
Comment (codyebberson) [inline packages/server/src/fhir/lookups/token.ts:445]: What is the case where `return undefined;`?

**Review by codyebberson — APPROVED** [review]

File: packages/server/src/fhir/lookups/token.ts (hunk 1 above)
Comment (rahul1) [reply packages/server/src/fhir/lookups/token.ts:119]: Kept, just moved to line 212
