### PR TITLE
Fixes #4365 - graphiql and external auth providers

### LINKED ISSUE #4365: Sign-in to graphiql fails if DomainConfiguration is present
Already in progress - just tracking

### PR DESCRIPTION
**Pull request by codyebberson**

### CODE REVIEW

File: packages/react/src/auth/AuthenticationForm.tsx [hunk 1]
```diff
@@ -51,15 +52,17 @@ export function EmailForm(props: EmailFormProps): JSX.Element {
   const issues = getIssuesForExpression(outcome, undefined);
 
   const isExternalAuth = useCallback(
-    async (authMethod: any): Promise<boolean> => {
+    async (authMethod: AuthMethodResponse): Promise<boolean> => {
```
Comment (ThatOneBro) [inline packages/react/src/auth/AuthenticationForm.tsx:55]: Nice

File: packages/react/src/auth/AuthenticationForm.tsx [hunk 2]
```diff
@@ -70,7 +73,7 @@ export function EmailForm(props: EmailFormProps): JSX.Element {
 
   const handleSubmit = useCallback(
     async (formData: Record<string, string>) => {
-      const authMethod = await medplum.post('auth/method', { email: formData.email });
+      const authMethod = await medplum.checkAuthMethod(formData.email);
```
Comment (ThatOneBro) [inline packages/react/src/auth/AuthenticationForm.tsx:76]: 👍

File: packages/server/src/auth/method.ts [hunk 3]
```diff
@@ -37,7 +37,7 @@ export async function methodHandler(req: Request, res: Response): Promise<void>
  * @param email - The user email address.
  * @returns External auth url if available. Otherwise undefined.
  */
-export async function isExternalAuth(email: string): Promise<{ domain: string; authorizeUrl: string } | undefined> {
+export async function isExternalAuth(email: string): Promise<AuthMethodResponse | undefined> {
```
Comment (ThatOneBro) [inline packages/server/src/auth/method.ts:40]: Clean

**Review by ThatOneBro — APPROVED** [review]
Nice, looks clean
