### PR TITLE
Fixes #8955 - use streaming for bulk export

### LINKED ISSUE #8955: Add streaming to bulk export
> Hello medplum! On the medplum CLI 4.5.2-515c26d74 we're experiencing an issue with the bulk export, it seems that our data has outgrown the nodejs limit for a string:
> 
> ```
> % medplum bulk export --types Patient
> node:internal/encoding:494
>         if (!chunk) return decodeUTF8(input, ignoreBom, this[kFatal]);
>                            ^
> 
> Error: Cannot create a string longer than 0x1fffffe8 characters
>     at TextDecoder.decode (node:internal/encoding:494:28)
>     at node:internal/blob:297:23
>     at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
>     at async /Users/brandon.aldrich/.nvm/versions/node/v22.14.0/lib/node_modules/@medplum/cli/dist/cjs/index.cjs:14:1466 {
>   code: 'ERR_STRING_TOO_LONG'
> }
> ```

We should add a streaming option.

### PR DESCRIPTION
**Pull request by codyebberson**

### CODE REVIEW

File: packages/cli/src/bulk.ts [hunk 1]
```diff
@@ -35,16 +38,23 @@ bulkExportCommand
     const medplum = await createMedplumClient(options);
     const response = await medplum.bulkExport(exportLevel, types, since, { pollStatusOnAccepted: true });
 
-    response.output?.forEach(async ({ type, url }) => {
+    for (const { type, url } of response.output ?? []) {
```
Comment (mattlong) [inline packages/cli/src/bulk.ts]:
```suggestion
    for (const { type, url } of response.output ?? EMPTY) {
```

**Review by The-Alchemist — APPROVED** [review]

**Review by mattlong — APPROVED** [review]
LGTM one baby suggestion
