### PR TITLE
Fixes #4365 Fixes #8673 - DomainConfiguration rules on external apps

### LINKED ISSUE #4365: Sign-in to graphiql fails if DomainConfiguration is present
Already in progress - just tracking

### LINKED ISSUE #8673: [bug] DomainConfiguration does not work when logging in from custom domain
## Repro
- DomainConfiguration set to `example.com`  to redirect to an Okta client
- User (admin@example.com) has multiple ProjetMemberships
- Start logging in to [provider.medplum.com](http://provider.medplum.com/)  with `admin@example.com`
- Log into Okta successfully
- we then redirect to [app.medplum.com](http://app.medplum.com/)  to select the specific project membership 

## Background
At [this point in the auth flow](https://github.com/medplum/medplum/blob/3fb7ee94e215ed941a5626fcd4ec57ccb3e5bc68/packages/server/src/auth/external.ts#L115-L150):
we DON’t have
- ClientId
- ProjectId
- Membership

Right now we are always redirected app.medplum.com to sign in

## Expected behavior
To select the project membership, you should be directed to the initiating sign in page

### PR DESCRIPTION
**Pull request by codyebberson**
This PR introduces a new optional field on `DomainConfiguration`:

```
allowedPostLoginRedirectUrls: string[]
```

#### Background

Some enterprise customers configure domain-level SSO policies (e.g. “all `@example.com` users must authenticate via Okta / Entra”), regardless of the `client_id` used.

This works well for Medplum-hosted apps, but creates challenges for custom applications:

* Domain-based IdP routing happens early in the login flow (before `client_id` / `redirect_uri` are known)
* After successful authentication, users need to be returned to the originating application
* Without safeguards, this introduces risk of open redirect vulnerabilities

#### What this change does

This PR allows domain configurations to explicitly define a set of **allowlisted post-login redirect URLs**.

During login:

1. If a domain-based IdP is triggered, the original sign-in URL is preserved in the auth state
2. After successful authentication, Medplum validates the URL against `allowedPostLoginRedirectUrls`
3. If valid, the user is redirected to that URL
4. Otherwise, the user falls back to the default Medplum app flow

#### Security considerations

* Redirects are only allowed to explicitly configured URLs
* Prevents open redirect vulnerabilities
* Does not change OAuth redirect URI validation (IdP callbacks still return to Medplum-owned endpoints)

#### Why this matters

* Enables domain-based SSO for developer-built apps
* Maintains compatibility with existing enterprise SSO configurations
* Provides a safe, explicit mechanism for post-login routing without requiring early `client_id` resolution

### CODE REVIEW

**Comment by codyebberson** [comment]
@claude please review

File: packages/server/src/auth/external.ts [hunk 1]
```diff
@@ -233,3 +247,44 @@ async function verifyExternalCode(
...
   }
 }
+
+/**
+ * Determines if the returnTo URL is valid based on the domain configuration.
+ * @param returnTo - The returnTo URL from the external auth state.
+ * @param domainConfig - The domain configuration for the external auth request.
+ * @returns True if the returnTo URL is valid, false otherwise.
+ */
+function validateReturnToUrl(
```
Comment (ThatOneBro) [inline packages/server/src/auth/external.ts]: Small nit, most of our validation functions that use the `validate` verb are functions that throws a validation error.

Maybe we could call this `isValidReturnToUrl()`?

File: packages/server/src/auth/external.ts [hunk 2]
```diff
@@ -233,3 +247,44 @@ async function verifyExternalCode(
...
+): returnTo is string {
+  if (!returnTo) {
+    return false;
+  }
+
+  try {
+    const returnToUrl = new URL(returnTo);
+
+    // Always allow .medplum.com hosts
+    if (returnToUrl.hostname.endsWith('.medplum.com')) {
```
Comment (mattlong) [inline packages/server/src/auth/external.ts]: Are we sure we want to add a hardcoded value here?

Comment (codyebberson) [reply packages/server/src/auth/external.ts]: Yeah, good point, this should probably be a config setting.

**Review by ThatOneBro — APPROVED** [review]

File: packages/server/src/auth/external.ts (hunk 1 above)
Comment (codyebberson) [reply packages/server/src/auth/external.ts]: Yep, done ✅

File: packages/server/src/auth/external.ts (hunk 2 above)
Comment (codyebberson) [reply packages/server/src/auth/external.ts]: Done ✅
