### PR TITLE
Fix agent channel reload when endpoint protocol changes

### LINKED ISSUE #6729: Changing agent channel protocol doesn't trigger channel type to change on reload
Changing the protocol of the channel endpoint (channels with same host and port but different protocol) are not correctly detected by the diff. This should result in the previous channel closing and a new channel of the correct type opening instead of a no-op.

### PR DESCRIPTION
**Pull request by degoke**
## What this fixes

This fixes a bug where changing a channel endpoint from one protocol to another on the same channel name was getting treated like a no-op reload.

So if a channel changed from something like `mllp://...` to `tcp://...`, we were reusing the existing channel instance instead of shutting down the old one and starting the right channel type.

## What changed

- if the existing channel type and the new endpoint type are the same, we still use the normal `reloadConfig()` path
- If the type changed, we now stop the old channel, remove it, create the right channel type, and start that instead
- pulled channel creation into a small helper so we don’t repeat the same switch in two places
- added coverage to the existing reload-config test to make sure a protocol change actually replaces the channel instance

## Testing

- ran the agent reload-config test
- verified same-type reloads still work
- verified protocol changes swap the channel instance instead of being ignored
- verified that the old channel gets closed after the replacement

Closes #6729

### CODE REVIEW

File: packages/agent/src/app.ts [hunk 1]
```diff
@@ -596,28 +596,39 @@ export class App {
...
+
+      if (previousType === nextType) {
+        await existingChannel.reloadConfig(definition, endpoint);
+        return;
+      }
+
+      await existingChannel.stop();
+      this.channels.delete(definition.name);
+
+      let replacementChannel: Channel;
```
Comment (ThatOneBro) [inline packages/agent/src/app.ts]: Instead of handling the replacement channel as a separate case, could we remove the rest of this block and just let it fall into the normal `createChannel` case?

**Review by ThatOneBro — COMMENTED** [review]
Looks great! One minor suggestion about removing a logically duplicate block for the replacement channel, but otherwise looks good for merge after that.

Thank you for your contribution! 🙏

File: packages/agent/src/app.ts (hunk 1 above)
Comment (degoke) [reply packages/agent/src/app.ts]: Yes we can, that way the block is not duplicated. I'll make an update

**Comment by degoke** [comment]
> Looks great! One minor suggestion about removing a logically duplicate block for the replacement channel, but otherwise looks good for merge after that.
> 
> Thank you for your contribution! 🙏  

Thank you for taking the time to review this! 🙏🏿 Medplum is an excellent project, and I plan to make more contributions as I get up to speed with the codebase.

**Comment by ThatOneBro** [comment]
Thank you @degoke !

We appreciate you taking interest in the project and truly value all our community contributors.

Your latest change looks great!

It looks like your last commit was not signed, do you mind doing:
`git commit --amend -s`
And then force-pushing your branch?

**Review by ThatOneBro — APPROVED** [review]
Thanks @degoke, great work 🙏 🚀
