### PR TITLE
fix(agent): no crash on startup when unable to connect

### LINKED ISSUE #6388: Agent crashes at startup if network is down before agent calls `MedplumClient.startClientLogin`

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #6388

### CODE REVIEW

File: packages/agent/src/app.ts [hunk 1]
```diff
@@ -269,13 +267,10 @@ export class App {
...
-    return new Promise<void>((resolve, reject) => {
-      const connectTimeout = setTimeout(
-        () => reject(new Error('Timeout when attempting to connect to server WebSocket')),
-        10000
-      );
+    return new Promise<void>((resolve) => {
+      const connectInterval = setInterval(() => this.webSocket?.reconnect(), RETRY_WAIT_DURATION_MS);
       this.webSocket?.addEventListener('open', () => {
-        clearTimeout(connectTimeout);
+        clearInterval(connectInterval);
```
Comment (codyebberson) [inline packages/agent/src/app.ts:273]: Nice, this makes sense.

File: packages/agent/src/agent-main.ts [hunk 2]
```diff
@@ -46,10 +47,32 @@ export async function agentMain(argv: string[]): Promise<App> {
   const { baseUrl, clientId, clientSecret, agentId } = args;
 
   const medplum = new MedplumClient({ baseUrl, clientId });
-  await medplum.startClientLogin(clientId, clientSecret);
+
+  let loggedIn = false;
+  while (!loggedIn) {
+    try {
+      await medplum.startClientLogin(clientId, clientSecret);
```
Comment (codyebberson) [inline packages/agent/src/agent-main.ts:54]: Hm, this might be too broad.  For example, if the client credentials are wrong, do we want to keep retrying?

File: packages/agent/src/agent-main.ts [hunk 3]
```diff
@@ -46,10 +47,32 @@ export async function agentMain(argv: string[]): Promise<App> {
...
+    }
+  }
 
   const app = new App(medplum, agentId, parseLogLevel(args.logLevel ?? 'INFO'));
-  await app.start();
+
+  let started = false;
+  while (!started) {
+    try {
+      await app.start();
```
Comment (codyebberson) [inline packages/agent/src/agent-main.ts:68]: Do we know what the conditions are that can fail at this point?

File: packages/agent/src/agent-main.ts (hunk 2 above)
Comment (ThatOneBro) [reply packages/agent/src/agent-main.ts:54]: Good point, we might want to only catch the fetch failed error?

File: packages/agent/src/agent-main.ts (hunk 3 above)
Comment (ThatOneBro) [reply packages/agent/src/agent-main.ts:68]: Yeah maybe it's actually not a good idea to catch here because there could be real errors we want to throw and stop the service. With restarts it should be more robust to that now anyways

Comment (ThatOneBro) [reply packages/agent/src/agent-main.ts:68]: In rare cases fetch could fail when attempting to fetch the config from Medplum server, but that should be pretty rare since we basically make sure we are connected in two spots before we get to that line (the call to `App.startWebSocket` just before and also the `startClientLogin` loop we have

File: packages/agent/src/agent-main.ts (hunk 2 above)
Comment (ThatOneBro) [reply packages/agent/src/agent-main.ts:54]: Ok after talking offline we decided to keep this since it will likely spin anyways after adding auto-restart of the service... in most cases this will fail due to network being disconnected so this is probably still fine
