### PR TITLE
Fixes #4026 - Binary.data prop, binaries in batches

### LINKED ISSUE #4026: Error uploading Binary in Transaction Bundle
## Repro
Upload the following Bundle
```json
{
  "type": "transaction",
  "resourceType": "Bundle",
  "entry": [
    {
      "fullUrl": "urn:uuid:a0010b42-02ea-411c-a314-9ec144f6c2b8",
      "request": {
        "method": "POST",
        "url": "Binary"
      },
      "resource": {
        "resourceType": "Binary",
        "contentType": "text/plain",
        "data": "SGVsbG8gV29ybGQh"
      }
    },
    {
      "request": {
        "method": "POST",
        "url": "DocumentReference"
      },
      "resource": {
        "resourceType": "DocumentReference",
        "status": "current",
        "content": [
          {
            "attachment": {
              "contentType": "text/plain",
              "url": "urn:uuid:a0010b42-02ea-411c-a314-9ec144f6c2b8"
            }
          }
        ]
      }
    }
  ]
}
```

## Observed Behavior
- Batch Uploads successfully
- Both `Binary` and `DocumentReference` resource created successfully
- However, navigating to the `storage.medplum.com/***` url in the `DocumentReference` brings up the following error:
 
image

## Expected Behavior
navigating to the `storage.medplum.com/***` url in the `DocumentReference` brings up a text file with "Hello World!"

### PR DESCRIPTION
**Pull request by codyebberson**
See #4026

### CODE REVIEW

File: packages/server/src/fhir/repo.ts [hunk 1]
```diff
@@ -521,13 +523,42 @@ export class Repository extends BaseRepository implements FhirRepository<PoolCli
...
+        this.push(buffer);
+        this.push(null); // Signifies the end of the stream (EOF)
+      },
+    });
+
+    // Write the stream to the binary storage
+    await getBinaryStorage().writeBinary(resource, undefined, resource.contentType, stream);
+
+    // Remove the data field from the resource
+    delete resource.data;
```
Comment (ThatOneBro) [inline packages/server/src/fhir/repo.ts:559]:
```suggestion
    resource.data = undefined;
```
Setting to `undefined` usually preferred imo, just because of complicated hidden class implications. And `undefined` is already allowed in the types 🤔 so should be ok?

**Review by ThatOneBro — APPROVED** [review]
LGTM, one minor comment

**Review by rahul1 — APPROVED** [review]
