### PR TITLE
fix(fhircast): align context change request with STU3

### LINKED ISSUE #5356: Allow using STU3 URLs for FHIRcast
We are trying to utilize the medplum client to interact with a third party fhircast hub which implements the STU3 spec where the hub topic can be defined in the body instead of being required on the url itself: https://hl7.org/fhir/uv/fhircast/2024May/2-6-RequestContextChange.html#request-context-change-example. Currently having to manually override the url:

```
  const { fetch: originalFetch } = window;

  window.fetch = async (...args) => {
    let [resource] = args;

    return await originalFetch(
      resource.toString().replace("fhircast/STU3", fhircastPrefix)
    );
  };
```

This should be supported if Medplum plans on supporting FHIR cast STU3: https://www.medplum.com/docs/fhircast. If this is already on the road map, apologies!

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #5356

### CODE REVIEW

File: packages/server/src/fhircast/routes.ts [hunk 1]
```diff
@@ -71,65 +71,42 @@ publicSTU3Routes.get('/.well-known/fhircast-configuration', (_req: Request, res:
...
+// Or publish an event depending on payload
 protectedCommonRoutes.post(
   '/',
-  [
-    body('hub.channel.type').notEmpty().withMessage('Missing hub.channel.type'),
-    body('hub.mode').notEmpty().withMessage('Missing hub.mode'),
-    body('hub.topic').notEmpty().withMessage('Missing hub.topic'),
-    body('hub.events').notEmpty().withMessage('Missing hub.events'),
-  ],
+  oneOf(
```
Comment (ThatOneBro) [inline packages/server/src/fhircast/routes.ts:78]: This is a way to validation of two different types of payloads. https://express-validator.github.io/docs/api/one-of/

One of them is the "subscription request"
The other is the "context change request"

File: packages/server/src/fhircast/routes.ts [hunk 2]
```diff
@@ -71,65 +71,42 @@ publicSTU3Routes.get('/.well-known/fhircast-configuration', (_req: Request, res:
...
-    if (type !== 'websocket') {
-      sendOutcome(res, badRequest('Invalid hub.channel.type'));
-      return;
-    }
-
-    const mode = req.body['hub.mode'] as 'subscribe' | 'unsubscribe';
-    if (!(['subscribe', 'unsubscribe'] as const).includes(mode)) {
-      sendOutcome(res, badRequest('Invalid hub.mode'));
+    // If there is an ID, this is a context change request
+    if (req.body.id) {
```
Comment (ThatOneBro) [inline packages/server/src/fhircast/routes.ts:105]: We check for `id` to determine whether its a context change request or subscription request

File: packages/server/src/fhircast/routes.ts [hunk 3]
```diff
@@ -140,40 +117,92 @@ protectedCommonRoutes.post(
...
+    await getRedis().del(`medplum:fhircast:topic:${event['hub.topic']}:latest`);
+  } else if (event['hub.event'] === 'DiagnosticReport-update') {
+    // See: https://build.fhir.org/ig/HL7/fhircast-docs/3-6-3-DiagnosticReport-update.html#:~:text=The%20Hub%20SHALL,the%20new%20updates.
+    event['context.priorVersionId'] = event['context.versionId'];
+    event['context.versionId'] = generateId();
+    stringifiedBody = JSON.stringify(req.body);
+    // TODO: Make sure this is actually supposed to be stored / overwrite open context? (ambiguous from docs, see: https://build.fhir.org/ig/HL7/fhircast-docs/2-9-GetCurrentContext.html)
+    await getRedis().set(`medplum:fhircast:topic:${event['hub.topic']}:latest`, stringifiedBody);
+  }
+  await getRedis().publish(event['hub.topic'], stringifiedBody);
```
Comment (ThatOneBro) [inline packages/server/src/fhircast/routes.ts:204]: The main change here is using `event['hub.topic']` instead of the `req.params.topic`

File: packages/server/src/fhircast/routes.ts [hunk 4]
```diff
@@ -71,65 +71,43 @@ publicSTU3Routes.get('/.well-known/fhircast-configuration', (_req: Request, res:
...
+        body('event.context').notEmpty().withMessage('Missing event.context'),
+      ],
+      [
+        body('hub.channel.type').notEmpty().withMessage('Missing hub.channel.type'),
+        body('hub.mode').notEmpty().withMessage('Missing hub.mode'),
+        body('hub.topic').notEmpty().withMessage('Missing hub.topic'),
+        body('hub.events').notEmpty().withMessage('Missing hub.events'),
+      ],
+    ],
+    { errorType: 'least_errored' }
```
Comment (ThatOneBro) [inline packages/server/src/fhircast/routes.ts:95]: `least_errored` error type means of the different groups, the one with the least errors is selected as our "choice", ie. the one for which the validation feedback is given back to the user in the case that neither group passes validation

File: packages/server/src/fhir/outcomes.ts [hunk 5]
```diff
@@ -1,20 +1,28 @@
...
-    issue: errors.array().map((error) => ({
-      severity: 'error',
-      code: 'invalid',
-      expression: getValidationErrorExpression(error),
-      details: { text: error.msg },
-    })),
+    issue: errors
+      .array()
+      .flatMap((error) => {
+        if (error.type === 'alternative') {
```
Comment (ThatOneBro) [inline packages/server/src/fhir/outcomes.ts:15]: Because of the `oneOf` syntax, we need to flat map all the errors out of the `nestedErrors` field in the case of `ValidationError` of type `alternative`, since the errors for each group are nested under one error.

File: packages/server/src/fhircast/routes.ts [hunk 6]
```diff
@@ -140,40 +118,92 @@ protectedCommonRoutes.post(
...
       stringifiedBody = JSON.stringify(req.body);
-      // TODO: Make sure this is actually supposed to be stored / overwrite open context? (ambiguous from docs, see: https://build.fhir.org/ig/HL7/fhircast-docs/2-9-GetCurrentContext.html)
-      await getRedis().set(`medplum:fhircast:topic:${req.params.topic}:latest`, stringifiedBody);
     }
-    await getRedis().publish(req.params.topic as string, stringifiedBody);
-    res.status(201).json({ success: true, event: body });
-  })
-);
+    // TODO: we need to get topic from event and not route param since per spec, the topic shouldn't be the slug like we have it
+    await getRedis().set(`medplum:fhircast:topic:${event['hub.topic']}:latest`, stringifiedBody);
```
Comment (codyebberson) [inline packages/server/src/fhircast/routes.ts:192]: While we're making these changes, should we move forward w/ namespacing these with project ID?

This is still open to potential topic ID collision, yeah?

**Review by codyebberson — APPROVED** [review]

File: packages/server/src/fhircast/routes.ts (hunk 6 above)
Comment (ThatOneBro) [reply packages/server/src/fhircast/routes.ts:192]: Yeah for sure. We can do that in the other `FHIRcast` PR, I think I'll have to rebase that PR once this PR gets merged:
https://github.com/medplum/medplum/pull/4951
