### PR TITLE
fix(subscriptions): reconnect on profile change

### LINKED ISSUE #5142: Changing profile in `MedplumClient` causes `useSubscription` to no longer receive updates

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #5142

### CODE REVIEW

**Comment by charlesbthomas** [comment]
Thanks @ThatOneBro

File: packages/core/src/subscriptions/index.ts [hunk 1]
```diff
@@ -247,6 +249,16 @@ export class SubscriptionManager {
         }, this.pingIntervalMs);
       }
     });
+
+    this.medplum.addEventListener('change', () => {
```
Comment (codyebberson) [inline packages/core/src/subscriptions/index.ts:253]: 👍

**Review by codyebberson — APPROVED** [review]
Nice 👍
