### PR TITLE
fix(client/subscription): prevent React lifecycles from tracking unused WebSocket subs

### LINKED ISSUE #8662: Investigate `SubscriptionManager` keeping untracked subscriptions bound to WebSocket
We've done a lot of work around garbage collection on the server side but a lot of the cleanup assumes that a user's client will either:
1) Unbind an unused subscription
2) Close the WebSocket, which when detected server-side will clean up all WebSocket subscriptions associated with that WebSocket connection

It seems like some of the particular patterns that emerge from React component lifecycles may make some race conditions possible which may untrack subscriptions in the `SubscriptionManager` without actually sending an unbind message. This means that a subscription will not be cleaned up until a user closes their WebSocket connection, which may not happen frequently enough to free up unused subscriptions from the perspective of the `SubscriptionManager`

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #8662

### CODE REVIEW

**Comment by codyebberson** [comment]
@claude please review

For context: websocket connect/disconnect lifecycle events have proven unreliable, and it feels like we might be fighting a losing battle of trying to rely on them. Is there a better way to do this, like maybe a "global list + GC" model?

File: packages/core/src/subscriptions/index.ts [hunk 1]
```diff
@@ -518,9 +580,41 @@ export class SubscriptionManager {
       return;
     }
 
-    // If actually removing (refcount === 0)
-    this.maybeEmitDisconnect(criteriaEntry);
-    this.removeCriteriaEntry(criteriaEntry);
+    // Record when refCount hit 0 — gcUnrefEntries will finalize after the grace period.
+    // Re-subscribing before then rescues the entry (see addCriteria).
+    criteriaEntry.lastUnrefTime = Date.now();
+    criteriaEntry.generation++;
```
Comment (mattwiller) [inline packages/core/src/subscriptions/index.ts]: Instead of early-returning above, the code could be aligned with this comment like so:
```ts
if (criteriaEntry.refCount <= 0) {
  criteriaEntry.lastUnrefTime = Date.now();
  criteriaEntry.generation++;
}
```

Comment (ThatOneBro) [reply packages/core/src/subscriptions/index.ts]: Good callout
