### PR TITLE
fix(hl7): use msg ctrl id to correlate resp for `Hl7Client.sendAndWait`

### LINKED ISSUE #7115: `Hl7Client.sendAndWait` does not handle enhanced-mode ACKs properly
Currently the `Hl7Client` naively returns the next message it receives from the server for the `sendAndWait` method, which with the enhanced mode ACK protocol, does not function as intended.

Whenever we return a CA (Commit Accept) ACK in enhanced mode, we expect an AA (Application Accept) ACK to be generated later, which the client does not currently take into account.

We should check that the  control ID matches the original message before returning an ACK for `sendAndWait`

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #7115

### CODE REVIEW

**Comment by codyebberson** [comment]
@claude please review

**Review by codyebberson — APPROVED** [review]
Structurally looks good to me.  Good to go after test coverage clears.

File: packages/hl7/src/connection.ts [hunk 1]
```diff
@@ -59,24 +76,59 @@ export class Hl7Connection extends Hl7Base {
...
+        return;
+      }
+
+      // Two modes:
+      // Application-level or first ACK
+
+      // First should always return on any ACK message, this is the default
+      // The exception is APPLICATION, which should not resolve when the ACK is a CA, but should resolve on all other ACK types
+      // On CA, we return early
+      if (queueItem.returnAck === ReturnAckCategory.APPLICATION && ackCode === 'CA') {
```
Comment (ThatOneBro) [inline packages/hl7/src/connection.ts:131]: The only case we really want to skip resolving the Promise when receiving in ACK is when:
1. The user opts into the APPLICATION-level ACK
2. The ACK code returned is a CA (all other C-level ACKs indicate early failure and probably that you won't get an applciation-level ACK)

**Review by codyebberson — APPROVED** [review]
