### PR TITLE
fix(client/auth): respect `accessToken` in constructor

### LINKED ISSUE #3065: `MedplumClient` constructor ignores `accessToken`
## Repro

- Log into Medplum app in browser
- Copy the medplum access token from local storage
- Create a Medplum client as follows
```
const medplum = new MedplumClient({
      fetch: async (url: string, options?: any) => await fetch(url, options),
      token: medplumToken 
    });
```
- Call `medplum.graphql(SOME_QUERY)`

## Expected Behavior
Query completes successfully

## Actual Behavior
Unauthenticated error

## Workaround
Call `medplum.setAccessToken`, rather than using constructor parameter

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #3065

### CODE REVIEW

File: packages/core/src/client.ts [hunk 1]
```diff
@@ -666,6 +666,10 @@ export class MedplumClient extends EventTarget {
       this.refreshProfile().catch(console.log);
     }
 
+    if (options?.accessToken) {
+      this.accessToken = options.accessToken;
```
Comment (mattwiller) [inline packages/core/src/client.ts:670]: We probably want to use `this.setAccessToken(options.accessToken)` here to ensure all the client state is set correctly

Comment (ThatOneBro) [reply packages/core/src/client.ts:670]: Good catch

File: packages/core/src/client.ts [hunk 2]
```diff
@@ -666,6 +666,10 @@ export class MedplumClient extends EventTarget {
       this.refreshProfile().catch(console.log);
     }
 
+    if (options?.accessToken) {
+      this.setAccessToken(options.accessToken);
+    }
```
Comment (codyebberson) [inline packages/core/src/client.ts:671]: Yep, this is the meat of it.

I think we should move lines 663-667 into an `else` block though, to avoid confusion.  If user passes in an `accessToken`, we're going to ignore existing login.

In practice, this is unlikely to matter too much (the use cases are pretty different), but I'd prefer to be explicit.

**Review by codyebberson — COMMENTED** [review]
Nice.  See comment on `getActiveLogin` code path.  Feel free to disagree.

**Comment by ThatOneBro** [comment]
> Nice. See comment on `getActiveLogin` code path. Feel free to disagree.

Nope, that makes sense to me. Shouldn't bother calling it if we provide an `accessToken`, totally agree.

**Review by codyebberson — APPROVED** [review]
