### PR TITLE
Fixes #4069 - validate choice-of-type cardinality

### LINKED ISSUE #4069: Not enforcing single value for choice-of-types
## Repro
Create the following resource: 
```
{
  "resourceType": "CarePlan",
  "subject": {
    "reference": "Patient/fdf33a83-08b0-4475-ae99-f5b6fec2f0f1",
    "display": "Homer Simpson"
  },
  "status": "active",
  "intent": "order",
  "id": "626cb499-60b0-46ad-a505-42d703294c17",
  "activity": [
    {
      "detail": {
        "status": "in-progress",
        "scheduledPeriod": {
          "start": "2024-02-29T16:52:20.825Z"
        },
        "scheduledTiming": {
          "repeat": {
            "period": 1,
            "periodUnit": "d"
          }
        }
      }
    }
  ]
}
```

## Expected Behavior
Error: only one of `scheduledPeriod` or `scheduledDateTime` can be specified

## Actual Behavior
Resource passes validation and is saved

### PR DESCRIPTION
**Pull request by codyebberson**
See #4069

This PR detects and logs the issue, but does not fail validation.

The plan is to log and monitor the issue, and give customers adequate time to fix any issues before enforcing.

### CODE REVIEW

**Review by reshmakh — APPROVED** [review]

File: packages/core/src/typeschema/validation.ts [hunk 1]
```diff
@@ -124,8 +133,18 @@ class ResourceValidator implements ResourceVisitor {
...
-    this.issues = []; // Reset issues to allow re-using the validator for other resources
-    if (issues.length > 0) {
+
+    let foundError = false;
+    for (const issue of issues) {
+      if (issue.severity === 'error') {
+        foundError = true;
+      }
+      if (issue.severity === 'warning' && this.options?.logger) {
+        this.options.logger.warn(`Validator warning: ${issue.details?.text}`, { issue });
```
Comment (rahul1) [inline packages/core/src/typeschema/validation.ts:143]: Does the logger include the projectId in the resulting log? It's really helpful for tracking down which customers are affected

Comment (codyebberson) [reply packages/core/src/typeschema/validation.ts:143]: ah, good call.  will add
