### PR TITLE
fix(agent): unwrap response for `$reload-config` by id

### LINKED ISSUE #4541: Calling `Agent/:id/$reload-config` should not return a bundle
We should establish a pattern that the bulk version of operations have a distinct payload from the single instance-level versions.

### PR DESCRIPTION
**Pull request by ThatOneBro**
Fixes #4541 

Later we may want to consider moving the bulk version of all endpoints to something like a `$bulk` operation which takes an `op` query parameter.

For example, `Agent/$bulk?op=reload-config&name:contains=Medplum` would perform a bulk reload-config on Agents with names containing `Medplum`...

I'll open a discussion about this later, but this PR should at least move in the right direction for now.

### CODE REVIEW

File: packages/core/src/outcomes.ts [hunk 1]
```diff
@@ -181,7 +181,7 @@ export function badRequest(details: string, expression?: string): OperationOutco
         details: {
           text: details,
         },
-        expression: expression ? [expression] : undefined,
+        ...(expression ? { expression: [expression] } : undefined),
```
Comment (codyebberson) [inline packages/core/src/outcomes.ts:184]: 🤔 

I suppose this avoids setting `expression: undefined`, but does that change anything in practice?

File: packages/server/src/fhir/operations/agentreloadconfig.ts [hunk 2]
```diff
@@ -47,7 +47,7 @@ async function reloadConfig(agent: Agent): Promise<FhirResponse> {
   }
 
   if (result.type === 'agent:error') {
-    throw new OperationOutcomeError(serverError(new Error(result.body)));
+    throw new OperationOutcomeError(badRequest(result.body));
```
Comment (codyebberson) [inline packages/server/src/fhir/operations/agentreloadconfig.ts:50]: 👍

File: packages/server/src/fhir/operations/utils/agentutils.ts [hunk 3]
```diff
@@ -108,6 +108,10 @@ export async function handleBulkAgentOperation(
     return [badRequest('No agent(s) for given query')];
   }
 
+  if (req.params.id) {
```
Comment (codyebberson) [inline packages/server/src/fhir/operations/utils/agentutils.ts:111]: 👍

**Review by codyebberson — APPROVED** [review]

File: packages/core/src/outcomes.ts (hunk 1 above)
Comment (ThatOneBro) [reply packages/core/src/outcomes.ts:184]: Yes, when I tried to compare a `badRequest` from over the wire with a `badRequest` instantiated, the strict equals failed since the newly created one had the extra `expression` key

Comment (ThatOneBro) [reply packages/core/src/outcomes.ts:184]: Since we remove keys with `undefined` values when sending over the wire
