### PR TITLE
fix(subscription): enable checking `AccessPolicy` for WS subs

### LINKED ISSUE #4205: Access Policies for Websockets Subscriptions only
Enforce AccessPolicies on websocket subscriptions only.
These subscriptions should use the AccessPolicy of ProjectMemberhsip that created them.

### PR DESCRIPTION
**Pull request by ThatOneBro**
Closes #4205

### CODE REVIEW

File: packages/server/src/workers/subscription.ts [hunk 1]
```diff
@@ -134,13 +134,19 @@ export function getSubscriptionQueue(): Queue<SubscriptionJobData> | undefined {
  *
  * Currently we log if the `AccessPolicy` is not satisfied only.
  *
- * TODO: Actually prevent notifications for `Subscriptions` where the `AccessPolicy` is not satisfied.
+ * TODO: Actually prevent notifications for `Subscriptions` where the `AccessPolicy` is not satisfied (for rest-hook subscriptins)
```
Comment (rahul1) [inline packages/server/src/workers/subscription.ts:137]: type
```suggestion
 * TODO: Actually prevent notifications for `Subscriptions` where the `AccessPolicy` is not satisfied (for rest-hook subscriptions)
```

File: packages/server/src/workers/subscription.ts [hunk 2]
```diff
@@ -157,6 +163,9 @@ async function checkAccessPolicy(resource: Resource, project: Project, subscript
             `[Subscription Access Policy]: Access Policy not satisfied on '${resourceReference}' for '${subReference}'`,
             { subscription: subReference, project: projectReference, accessPolicy }
           );
+          if (subscription.channel.type === 'websocket') {
```
Comment (rahul1) [inline packages/server/src/workers/subscription.ts:166]: Consolidate with a single ` if (subscription.channel.type === 'websocket') {}` at the end. 

This will make it easier to remove this case later

File: packages/server/src/workers/subscription.ts (hunk 1 above)
Comment (ThatOneBro) [reply packages/server/src/workers/subscription.ts:137]: Good catch

File: packages/server/src/workers/subscription.ts [hunk 3]
```diff
@@ -180,7 +181,10 @@ async function checkAccessPolicy(resource: Resource, project: Project, subscript
       `[Subscription Access Policy]: Error occurred while checking access policy for resource '${resourceReference}' against '${subReference}'`,
       { error: err, subscription: subReference }
     );
+    satisfied = false;
   }
+  // Always return true if channelType !== websocket for now
+  return subscription.channel.type === 'websocket' ? satisfied : true;
```
Comment (codyebberson) [inline packages/server/src/workers/subscription.ts:187]: Nice, I think this is the safe strategy for now 👍

**Review by codyebberson — APPROVED** [review]
